# Generated by Django 4.2 on 2023-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="music",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
