# Generated by Django 4.2 on 2023-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="artist",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
